#if !canImport(ObjectiveC)
import XCTest

extension PersistableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PersistableTests = [
        ("testEmptyArrayDeletesValueOnUserDefaults", testEmptyArrayDeletesValueOnUserDefaults),
        ("testEmptyValue", testEmptyValue),
        ("testIntArrayOnUserDefaults", testIntArrayOnUserDefaults),
        ("testKeychainPersistable", testKeychainPersistable),
        ("testKeychainPersistableOnUserDefaults", testKeychainPersistableOnUserDefaults),
        ("testMockCodableOnKeychain", testMockCodableOnKeychain),
        ("testMockCodableOnUserDefaults", testMockCodableOnUserDefaults),
        ("testPersistanceKeyRepresentable", testPersistanceKeyRepresentable),
        ("testStringArrayOnKeychain", testStringArrayOnKeychain),
        ("testStringOnUserDefaults", testStringOnUserDefaults),
        ("testUserDefaultsPersistable", testUserDefaultsPersistable),
    ]
}

extension SecureStorageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SecureStorageTests = [
        ("testDelete", testDelete),
        ("testDeleteOnPersistableType", testDeleteOnPersistableType),
        ("testOverwrite", testOverwrite),
        ("testSave", testSave),
        ("testSaveOnPersistableType", testSaveOnPersistableType),
    ]
}

extension UserDefaultsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserDefaultsTests = [
        ("testDelete", testDelete),
        ("testOverwrite", testOverwrite),
        ("testSave", testSave),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PersistableTests.__allTests__PersistableTests),
        testCase(SecureStorageTests.__allTests__SecureStorageTests),
        testCase(UserDefaultsTests.__allTests__UserDefaultsTests),
    ]
}
#endif
